PATHS:
  - pd_ids_mmd/cvae_ids
  - pd_ids_mmd/vanilla
  - pd_ids_mmd/qda_20
  - pd_ids_mmd/qda_30
  - pd_ids_mmd/gr_100
  - pd_ids_mmd/gr_125
  - pd_ids_mmd/gr_125

OUT: /mnt/home/jwu10/working/ceph/results/vae/pd_ids_mmd/