PATHS:
  - pd_ids_small/cvae_ids
  - pd_ids_small/vanilla
  - pd_ids_small/qda_20
  - pd_ids_small/qda_30
  - pd_ids_small/gr_100
  - pd_ids_small/gr_125
  - pd_ids_small/gr_150

OUT: /mnt/home/jwu10/working/ceph/results/vae/pd_ids_small/