PATHS:
  # - immunostain/cvae
  # - immunostain/vanilla
  - immunostain/cvae_mf
  - immunostain/vanilla_mf
  # - pd_speed/mi_10
  # - pd_speed/mi_100
  - pd_speed/mi_500
  # - pd_speed/mi_100_bw25_4k_10
  - pd_speed/mi_300_bw25_4k_mals_04
  - pd_speed/mi_500_bw25_4k_mals_04
  # - pd_speed/mi_500_bw25_4k_10
  # - pd_speed/mi_mals
  # - pd_speed/mi_100_bw25_10
  # - pd_speed/mi_200_bw25_10
  # - pd_speed/mi_300_bw10_4k_10_mals
  # - pd_speed/mi_500_bw25_10_mals
  # - pd_speed/mi_750_bw25_mals
  - pd_speed/mi_750_mals
  - pd_mals/mals_p1_10
  - pd_mals/mals_p1_20
  - pd_mals/mals_p1_50
  # - pd_speed/gr

OUT: /mnt/home/jwu10/working/ceph/results/vae/pd_mals/