PATHS:
  - beta_prior/cvae_g
  - beta_prior/mi_500_50_g
  - beta_prior/mi_500_100_g
  - beta_prior/vanilla
  - beta_prior/cvae_b
  - beta_prior/mi_500_50_b
  - beta_prior/mi_500_100_b

OUT: /mnt/home/jwu10/working/ceph/results/vae/beta_prior/