# heading:
#   - - "VAE"
#     - "vanilla/64"
#     - 300
#   - - "C-VAE"
#     - "mals_64/cvae_64"
#     - 280
#   - - "SC-VAE-GR"
#     - "gr_64/50"
#     - 490
#   - - "SC-VAE-MALS"
#     - "mals_64/mals_p1_20"
#     - 350
#   - - "SC-VAE-MI"
#     - "mi_64/bw50_500"
#     - 320

avg_speed_3d:
  - - "VAE"
    - "vanilla_64/1"
    - 300
  - - "C-VAE"
    - "cvae_64/1"
    - 275
  - - "SC-VAE-GR"
    - "gr_64/20_mf"
    - 320
  - - "SC-VAE-MALS"
    - "mals_64_mf/mals_p1_50"
    - 550
  - - "SC-VAE-MI"
    - "mi_64_mf/bw50_500"
    - 270

# ids:
#   - - "VAE"
#     - "vanilla/64"
#     - 500
#   - - "C-VAE"
#     - "ids_64/cvae_ids"
#     - 120
#   - - "VAE-GR"
#     - "ids_64/no_c_gr_100"
#     - 480
#   - - "SC-VAE-GR"
#     - "ids_64/gr_100"
#     - 480
#   - - "VAE-QD"
#     - "ids_64/no_c_qda_20"
#     - 485
#   - - "SC-VAE-QD"
#     - "ids_64/qda_20"
#     - 600

# pd_ids:
#   - - "VAE"
#     - "immunostain/vanilla_mf"
#     - 216
#   - - "C-VAE"
#     - "pd_ids/cvae_ids"
#     - 200
#   - - "SC-VAE-GR"
#     - "pd_ids/gr_50"
#     - 410
#   - - "SC-VAE-QD"
#     - "pd_ids/qda_10"
#     - 295

# pd_speed:
#   - - "VAE"
#     - "immunostain/vanilla_mf"
#     - 216
#   - - "C-VAE"
#     - "immunostain/cvae_mf"
#     - 214
#   - - "SC-VAE-MALS"
#     - "pd_mals/mals_p1_20"
#     - 400
#   - - "SC-VAE-MI"
#     - "pd_speed/mi_500"
#     - 216

# pd_ids_mmd:
#   - - "VAE"
#     - "pd_ids_mmd/vanilla"
#     - 175
#   - - "C-VAE"
#     - "pd_ids_mmd/cvae_ids"
#     - 175
#   - - "SC-VAE-GR"
#     - "pd_ids_mmd/gr_100"
#     - 175
#   - - "SC-VAE-QD"
#     - "pd_ids_mmd/qda_20"
#     - 155

OUT: /mnt/home/jwu10/working/SC-VAE/test_code/results/